---
name: 'Execute Manual Workflow'
description: 'Execute a manual workflow based on .'

inputs:
  branch_name:
    description: 'The branch name to execute the workflow on.'
    required: false
    default: "master"
  github_token:
    description: 'The GitHub Token. (Required if github_app_id and github_app_private_key are not provided)'
    required: false
  github_organization_name:
    description: 'The GitHub organization name.'
    required: true
  github_repository_name:
    description: 'The repository name.'
    required: true
  workflow_id:
    description: 'The workflow ID.'
    required: true
  workflow_inputs:
    description: 'The workflow inputs. Valid format: "--field key1=value1 --field key2=value2"'
    required: false
    default: ""
  workflow_watch:
    description: 'Whether to watch the workflow run or not. If true, the workflow will wait for the workflow to finish.'
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - id: exec-workflow
      name: Execute Workflow
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        gh workflow run --repo ${{ inputs.github_organization_name }}/${{ inputs.github_repository_name }} ${{ inputs.workflow_id }} --ref ${{ inputs.branch_name }} ${{ inputs.workflow_inputs }}
      shell: bash

    - id: watch-workflow
      if: inputs.workflow_watch == 'true'
      name: Watch Workflow
      run: |
        echo "Workflow is running."
      shell: bash