---
name: 'Build & Push Docker image'
description: 'Build and Push Docker image using default tags'
inputs:
  app_name:
    description: 'Name of the app to deploy.'
    required: true
    type: string
  artifact_region:
    description: 'Region or zone for Google Artifact Registry.'
    required: false
    type: string
    default: 'europe'
  artifact_repository_name:
    description: 'Name of the repo to upload image: ${url}/${repo}/${app}.'
    required: false
    type: string
  branch_name:
    description: 'Current branch name.'
    required: true
    type: string
  context:
    description: 'Context to build image (default: ./).'
    required: false
    type: string
    default: './'
  file:
    description: 'Path to Dockerfile.'
    required: false
    type: string
    default: 'Dockerfile'
  image_tag:
    description: 'Tags for the docker image.'
    required: true
    type: string
  push:
    description: 'Whether to push image to registry, or build locally.'
    required: false
    type: bool
    default: true

runs:
  using: 'composite'
  steps:
    - run: |-
        if [[ -z "${{ inputs.artifact_repository_name }}" ]]; then
          echo "REPO_URL=${{ inputs.artifact_region }}-docker.pkg.dev/fcm-platform-artifacts-ceba/${{ inputs.app_name }}/${{ inputs.app_name }}" >> $GITHUB_ENV
        else
          echo "REPO_URL=${{ inputs.artifact_region }}-docker.pkg.dev/fcm-platform-artifacts-ceba/${{ inputs.artifact_repository_name }}/${{ inputs.app_name }}" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: "Pull, Build & push Docker image [branch tag]"
      if: inputs.branch_name != 'master' && inputs.branch_name != 'main'
      shell: bash
      run: |
        docker pull ${{ env.REPO_URL }}:${{ inputs.branch_name }} || true
        docker build \
        --cache-from='${{ env.REPO_URL }}:${{ inputs.branch_name }}' \
        -t '${{ env.REPO_URL }}:${{ inputs.branch_name }}' \
        -t '${{ env.REPO_URL }}:${{ inputs.image_tag }}' \
        --build-arg BUILDKIT_INLINE_CACHE='1' \
        -f './Dockerfile' '.'

    # - name: "Pull Docker image [latest] for Buildx Cache"
    #   if: inputs.branch_name == 'master' || inputs.branch_name == 'main'
    #   shell: bash
    #   run: |
    #     docker pull ${{ env.REPO_URL }}:${{ inputs.branch_name }} || true
    #     docker pull ${{ env.REPO_URL }}:latest || true

    # - name: "Build & push Docker image [branch tag] + [latest tag]"
    #   uses: docker/build-push-action@v5
    #   if: inputs.branch_name == 'master' || inputs.branch_name == 'main'
    #   with:
    #     push: ${{ inputs.push }}
    #     file: ${{ inputs.file }}
    #     # cache-from: type=registry,ref=${{ env.REPO_URL }}:${{ inputs.branch_name }}
    #     cache-from: ${{ env.REPO_URL }}:${{ inputs.branch_name }}
    #     context: ${{ inputs.context }}
    #     tags: |
    #       ${{ env.REPO_URL }}:${{ inputs.branch_name }}
    #       ${{ env.REPO_URL }}:${{ inputs.image_tag }}
    #       ${{ env.REPO_URL }}:latest
    #     build-args: |
    #       BUILDKIT_INLINE_CACHE=1


