---
name: 'Build & Push Docker image'
description: 'Build and Push Docker image using default tags'
inputs:
  app_name:
    description: 'Name of the app to deploy.'
    required: true
    type: string
  artifact_region:
    description: 'Region or zone for Google Artifact Registry.'
    required: false
    type: string
    default: 'europe'
  artifact_repository_name:
    description: 'Name of the repo to upload image: ${url}/${repo}/${app}.'
    required: false
    type: string
  branch_name:
    description: 'Current branch name.'
    required: true
    type: string
  context:
    description: 'Context to build image (default: ./).'
    required: false
    type: string
    default: './'
  file:
    description: 'Path to Dockerfile.'
    required: false
    type: string
    default: 'Dockerfile'
  image_tag:
    description: 'Tags for the docker image.'
    required: true
    type: string
  push:
    description: 'Whether to push image to registry, or build locally.'
    required: false
    type: bool
    default: true

runs:
  using: 'composite'
  steps:
    - run: |-
        if [[ -z "${{ inputs.artifact_repository_name }}" ]]; then
          echo "REPO_URL=${{ inputs.artifact_region }}-docker.pkg.dev/fcm-platform-artifacts-ceba/${{ inputs.app_name }}/${{ inputs.app_name }}" >> $GITHUB_ENV
        else
          echo "REPO_URL=${{ inputs.artifact_region }}-docker.pkg.dev/fcm-platform-artifacts-ceba/${{ inputs.artifact_repository_name }}/${{ inputs.app_name }}" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: "Pull, Build & Push Docker image [branch tag] + [image tag]"
      uses: docker/build-push-action@v5
      if: inputs.branch_name != 'master' && inputs.branch_name != 'main'
      with:
        push: ${{ inputs.push }}
        pull: true
        file: ${{ inputs.file }}
        cache-from: |
          type=registry,ref=${{ env.REPO_URL }}:${{ inputs.branch_name }}
          type=registry,ref=${{ env.REPO_URL }}:latest
        cache-to: type=inline
        context: ${{ inputs.context }}
        tags: |
          ${{ env.REPO_URL }}:${{ inputs.branch_name }}
          ${{ env.REPO_URL }}:${{ inputs.image_tag }}

    - name: "Pull, Build & Push Docker image [branch tag] + [image tag] + [latest]"
      uses: docker/build-push-action@v5
      if: inputs.branch_name == 'master' || inputs.branch_name == 'main'
      with:
        push: ${{ inputs.push }}
        pull: true
        file: ${{ inputs.file }}
        cache-from: |
          type=registry,ref=${{ env.REPO_URL }}:${{ inputs.branch_name }}
          type=registry,ref=${{ env.REPO_URL }}:latest
        cache-to: type=inline
        context: ${{ inputs.context }}
        tags: |
          ${{ env.REPO_URL }}:${{ inputs.branch_name }}
          ${{ env.REPO_URL }}:${{ inputs.image_tag }}
          ${{ env.REPO_URL }}:latest
