---
name: 'ArgoCD CLI Sync App'
description: 'ArgoCD CLI commands for App force syncing.'

inputs:
  argocd_app_name:
    required: true
    type: string
    description: 'ArgoCD app name to be synchronized.'
  argocd_url:
    required: false
    type: string
    default: 'argocd.fcm.digital'
    description: 'ArgoCD URL (default: argocd.fcm.digital).'
  argocd_auth_token:
    required: true
    type: string
    description: 'ArgoCD auth token with get/sync permissions over apps.'

runs:
  using: "composite"
  steps:
    - id: argocd-cli-sync-app
      name: 'ArgoCD CLI Sync app'
      shell: bash
      run: argocd app sync ${{ inputs.argocd_app_name }} --server ${{ inputs.argocd_url }} --auth-token ${{ inputs.argocd_auth_token }} --retry-limit 10 --retry-backoff-duration 10s --retry-backoff-factor 2