---
name: 'ArgoCD CLI Sync App'
description: 'ArgoCD CLI commands for App force syncing.'

inputs:
  app_name:
    description: 'Name of the app to deploy.'
    required: true
  app_region:
    description: 'Region of the app to deploy.'
    required: true
  argocd_auth_token:
    description: 'ArgoCD auth token with get/sync permissions over apps.'
    required: true
  argocd_url:
    description: 'ArgoCD URL (default: argocd.fcm.digital).'
    required: false
    default: 'argocd.fcm.digital'
  branch_name:
    description: 'Current branch name.'
    required: true
  changelog_slack_message:
    description: 'If true, the action will output the live/current image tag.'
    required: false
    default: 'false'
  env_to_deploy:
    description: 'Environment where the image will be deployed.'
    required: true
  label_filter:
    description: 'Label key/value to be used as a filter for selecting resources.'
    required: false
  resources_filter:
    description: 'Resources type_name to be used as a filter for selecting resources.'
    required: false
  ignore_resources_filter:
    description: 'Resources type_name to be used as a filter for ignoring resources.'
    required: false

outputs:
  live_image_tag:
    description: 'The current Branch name.'
    value: ${{ steps.get-live-image-tag.outputs.live_image_tag }}

runs:
  using: "composite"
  steps:
    - id: get-live-image-tag
      if: inputs.changelog_slack_message == 'true' && inputs.env_to_deploy == 'prod'
      name: Get live Image Tag
      shell: bash
      run: ${{ github.action_path }}/get_live_imagetag_entrypoint.sh
      env:
        APP_NAME: ${{ inputs.app_name }}
        APP_REGION: ${{ inputs.app_region }}
        ARGOCD_AUTH_TOKEN: ${{ inputs.argocd_auth_token }}
        ARGOCD_URL: ${{ inputs.argocd_url }}
        ENV_TO_DEPLOY: ${{ inputs.env_to_deploy }}

    - id: argocd-resources-filter
      if: inputs.env_to_deploy != 'prod'
      name: 'ArgoCD CLI resources filter'
      run: |
        if [ -n "${{ inputs.resources_filter }}" ]; then
          filter_params=$( echo inputs.resources_filter | awk '{for(i=1;i<=NF;i++) printf "-e %s ", $i}' )
          resources_to_sync=$( argocd app resources ${{ inputs.app_name }}-${{ inputs.env_to_deploy }}-stg-${{ inputs.app_region }} | awk '$NF == "No" {print $(NF-3) "_" $(NF-1)}' | grep $filter_params )
        elif [ -n "${{ inputs.ignore_resources_filter }}" ]; then
          filter_params=$( echo inputs.ignore_resources_filter | awk '{for(i=1;i<=NF;i++) printf "-e %s ", $i}' )
          resources_to_sync=$( argocd app resources ${{ inputs.app_name }}-${{ inputs.env_to_deploy }}-stg-${{ inputs.app_region }} | awk '$NF == "No" {print $(NF-3) "_" $(NF-1)}' | grep -v $filter_params )
        else
          resources_to_sync=""
        fi
        
        if [ -z "$resources_to_sync" ]; then
          echo "resources_filter=" >> $GITHUB_OUTPUT
        else
          echo "resources_filter=$( echo "$resources_to_sync" | sed 's/_/:/g' | awk '{for(i=1;i<=NF;i++) printf "--resource '"'*:%s'"' ", $i}' )" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - id: argocd-cli-sync-app
      if: steps.argocd-resources-filter.outcomes == 'success'
      name: 'ArgoCD CLI Sync app'
      run: ${{ github.action_path }}/sync_app_entrypoint.sh
      env:
        APP_NAME: ${{ inputs.app_name }}
        APP_REGION: ${{ inputs.app_region }}
        ARGOCD_AUTH_TOKEN: ${{ inputs.argocd_auth_token }}
        ARGOCD_URL: ${{ inputs.argocd_url }}
        BRANCH_NAME: ${{ inputs.branch_name }}
        ENV_TO_DEPLOY: ${{ inputs.env_to_deploy }}
        LABEL_FILTER: ${{ inputs.label_filter }}
        RESOURCES_FILTER: ${{ steps.argocd-resources-filter.outputs.resources_filter }}
      shell: bash