---
name: 'ArgoCD CLI Sync App'
description: 'ArgoCD CLI commands for App force syncing.'

inputs:
  app_name:
    description: 'Name of the app to deploy.'
    required: true
    type: string
  app_region:
    description: 'Region of the app to deploy.'
    required: true
    type: string
  argocd_auth_token:
    description: 'ArgoCD auth token with get/sync permissions over apps.'
    required: true
    type: string
  argocd_url:
    description: 'ArgoCD URL (default: argocd.fcm.digital).'
    required: false
    type: string
    default: 'argocd.fcm.digital'
  branch_name:
    description: 'Current branch name.'
    required: true
    type: string
  env_to_deploy:
    description: >
      Environment where the image will be deployed.
      If the value is 'ALL_ENV', then all environments will be updated.
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - id: argocd-cli-sync-app
      name: 'ArgoCD CLI Sync app'
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        APP_NAME: ${{ inputs.app_name }}
        APP_REGION: ${{ inputs.app_region }}
        ARGOCD_AUTH_TOKEN: ${{ inputs.argocd_auth_token }}
        ARGOCD_URL: ${{ inputs.argocd_url }}
        BRANCH_NAME: ${{ inputs.branch_name }}
        ENV_TO_DEPLOY: ${{ inputs.env_to_deploy }}
      shell: bash