---
name: 'Checkout Repositories'
description: 'Checkout repositories and init context variables for ArgoCD deployment.'

inputs:
  app_name:
    description: 'App Name to Deploy.'
    required: true

  branch_name:
    description: 'Branch Name to Checkout (Required for manual deploy).'
    required: false
  env_to_deploy:
    description: 'Target Environment to Deploy. (Required for manual deploy).'
    required: false
  image_tag: 
    description: 'Image Tag to Deploy. If not provided, the image will be built from the workflow branch.'
    required: false

  github_token_checkout:
    description: 'The GitHub token to checkout helm_chart_template repository.'
    required: true
  helm_chart_template_ref:
    description: 'If provided, the helm-chart-template repository will be checked out to this branch.'
    required: false

outputs:
  branch_name:
    description: 'The name of the branch being deployed.'
    value: ${{ steps.init-context-vars.outputs.branch_name }}
  env_to_deploy:
    description: 'The target environment for deployment.'
    value: ${{ steps.init-context-vars.outputs.env_to_deploy }}
  commit_at:
    description: 'The timestamp of the commit.'
    value: ${{ steps.init-context-vars.outputs.current_time }}
  commit:
    description: 'The unique identifier for the commit.'
    value: ${{ steps.init-context-vars.outputs.short_sha }}
  image_tag:
    description: 'The tag of the new image to be deployed.'
    value: ${{ steps.init-context-vars.outputs.image_tag }}

runs:
  using: "composite"
  steps:
    - id: init-context-vars
      name: Init Context Variables
      run: |
        if [[ "${{ github.event_name }}" == 'workflow_dispatch' ]]; then
          if [[ -z "${{ inputs.branch_name }}" ]]; then
            echo "# 🚨 Checkout failed" > $GITHUB_STEP_SUMMARY
            echo "## Reason" >> $GITHUB_STEP_SUMMARY
            echo "Branch name not provided in a \`workflow_dispatch\` event." >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            export BRANCH_NAME=${{ inputs.branch_name }}
          fi

          if [[ -z "${{ inputs.env_to_deploy }}" ]]; then
            echo "# 🚨 Checkout failed" > $GITHUB_STEP_SUMMARY
            echo "## Reason" >> $GITHUB_STEP_SUMMARY
            echo "Environment not provided in a \`workflow_dispatch\` event." >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            export ENV_TO_DEPLOY=${{ inputs.env_to_deploy }}
          fi

        else
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            export BRANCH_NAME=${{ github.head_ref }}

            echo "The \`env_to_deploy\` extraction from the \`branch_name\` in a PR event is no longer available."
            echo "You must use the \`argocd-get-env-to-deploy-on\` action to obtain the \`env_to_deploy\` value."
            export ENV_TO_DEPLOY=NOT_DEFINED

          elif [[ "${{ github.event_name }}" == "push" ]]; then
            export BRANCH_NAME=${{ github.ref_name }}

            if [[ "${{ github.ref }}" == "refs/heads/master" || "${{ github.ref }}" == "refs/heads/main" ]]; then
              export ENV_TO_DEPLOY=prod
            else
              export ENV_TO_DEPLOY=${{ github.ref_name }}
            fi

          else
            echo "# 🚨 Checkout failed" > $GITHUB_STEP_SUMMARY
            echo "## Reason" >> $GITHUB_STEP_SUMMARY
            echo "Event \`${{ github.event_name }}\` not supported." >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
        fi

        if [[ -z "${{ inputs.image_tag }}" ]]; then
          export COMMIT_TIME=$( git show -s --format=%ct )
          export CURRENT_TIME=$( date -d@$COMMIT_TIME -u +"%Y-%m-%dT%H%M")
          export SHORT_SHA=$( git rev-parse --short=7 "$GITHUB_SHA" )
          export IMAGE_TAG=$BRANCH_NAME-$CURRENT_TIME-$SHORT_SHA
        else
          export CURRENT_TIME=NO_TIME
          export SHORT_SHA=NO_SHA
          export IMAGE_TAG=${{ inputs.image_tag }}
        fi

        echo "branch_name=$( echo $BRANCH_NAME )" >> $GITHUB_OUTPUT
        echo "env_to_deploy=$( echo $ENV_TO_DEPLOY )" >> $GITHUB_OUTPUT
        echo "current_time=$( echo $CURRENT_TIME )" >> $GITHUB_OUTPUT
        echo "short_sha=$( echo $SHORT_SHA )" >> $GITHUB_OUTPUT
        echo "image_tag=$( echo $IMAGE_TAG )" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch_name }}

    - uses: actions/checkout@v4
      if: github.event_name == 'push' && 
          (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main') &&
          steps.init-context-vars.outputs.env_to_deploy == 'prod' &&
          (steps.init-context-vars.outputs.branch_name == 'master' || steps.init-context-vars.outputs.branch_name == 'main')
      with:
        repository: fcm-digital/helm-chart-${{ inputs.app_name }}-values
        token: ${{ inputs.github_token_checkout }}
        ref: ${{ steps.init-context-vars.outputs.branch_name }}
        path: helm-chart-${{ inputs.app_name }}-values-prod

    - uses: actions/checkout@v4
      with:
        repository: fcm-digital/helm-chart-${{ inputs.app_name }}-values
        token: ${{ inputs.github_token_checkout }}
        ref: staging
        path: helm-chart-${{ inputs.app_name }}-values-staging

    - uses: actions/checkout@v4
      if: inputs.helm_chart_template_ref != ''
      with:
        repository: fcm-digital/helm-chart-template
        token: ${{ inputs.github_token_checkout }}
        ref: ${{ inputs.helm_chart_template_ref }}
        path: helm-chart-template