---
name: 'Checkout Repositories (Local & helm-chart-template)'
description: 'Checkout repositories and init all variables needed for Argocd deployment.'

inputs:
  github_ref_name:
    required: true
    type: string
    description: 'The branch or tag name that triggered the workflow run.'
  github_token_checkout:
    required: true
    type: string
    description: 'The GitHub token to checkout helm_chart_template repository'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - run: |
        export COMMIT_TIME=$( git show -s --format=%ct )
        echo "TIME=$( date -d@$COMMIT_TIME -u +"%Y-%m-%dT%H%M")" >> $GITHUB_ENV
        echo "SHORT_SHA=$( git rev-parse --short=7 HEAD )" >> $GITHUB_ENV
        echo "CURRENT_ENV=$( cut -d '-' -f 1 <<< "${{ inputs.github_ref_name }}" )" >> $GITHUB_ENV
        echo "BRANCH_NAME=${{ inputs.github_ref_name }}" >> $GITHUB_ENV
      shell: bash
    
    - uses: actions/checkout@v3
      with:
        repository: fcm-digital/helm-chart-template
        token: ${{ inputs.github_token_checkout }}
        ref: master
        path: helm-chart-template

    - run: printenv
      shell: bash
