---
name: 'Checkout Repositories'
description: 'Checkout repositories (Local & helm-chart-app-values) for ArgoCD deployment.'

inputs:
  app_name:
    description: 'Name of the app to deploy.'
    required: true
    type: string
  github_token_checkout:
    description: 'The GitHub token to checkout helm_chart_template repository.'
    required: true
    type: string
  helm_chart_template_ref:
    description: 'The helm-chart-template branch name.'
    required: false
    type: string
    default: master

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - run: |
        export COMMIT_TIME=$( git show -s --format=%ct )
        if [[ '${{ github.event_name }}' == 'pull_request' ]]; then
          export BRANCH_NAME_LOCAL=$( echo $GITHUB_HEAD_REF )
        elif [[ '${{ github.event_name }}' == 'push' ]]; then
          export BRANCH_NAME_LOCAL=$( cut -d '/' -f 3 <<< "$GITHUB_REF" )
        else
          exit 1
        fi
        echo "BRANCH_NAME=$( echo $BRANCH_NAME_LOCAL )'" >> $GITHUB_OUTPUT

        echo "CURRENT_ENV='$( cut -d '-' -f 1 <<< "$BRANCH_NAME_LOCAL" )'" >> $GITHUB_OUTPUT
        echo "TIME='$( date -d@$COMMIT_TIME -u +"%Y-%m-%dT%H%M")'" >> $GITHUB_OUTPUT
        echo "SHORT_SHA='$( git rev-parse --short=7 HEAD )'" >> $GITHUB_OUTPUT
        echo "testtesttest='12345'" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/checkout@v3
      with:
        repository: fcm-digital/helm-chart-template
        token: ${{ inputs.github_token_checkout }}
        ref: ${{ inputs.helm_chart_template_ref }}
        path: helm-chart-template

    - uses: actions/checkout@v3
      if: env.BRANCH_NAME == 'master' || env.BRANCH_NAME == 'main'
      with:
        repository: fcm-digital/helm-chart-${{ inputs.app_name }}-values
        token: ${{ inputs.github_token_checkout }}
        ref: ${{ env.BRANCH_NAME }}
        path: helm-chart-${{ inputs.app_name }}-values-prod

    - uses: actions/checkout@v3
      with:
        repository: fcm-digital/helm-chart-${{ inputs.app_name }}-values
        token: ${{ inputs.github_token_checkout }}
        ref: staging
        path: helm-chart-${{ inputs.app_name }}-values-staging
