---
name: 'Checkout Repositories'
description: 'Checkout repositories (Local & helm-chart-app-values) for ArgoCD deployment.'

inputs:
  app_name:
    description: 'Name of the app to deploy.'
    required: true
    type: string
  github_token_checkout:
    description: 'The GitHub token to checkout helm_chart_template repository.'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    # - uses: actions/checkout@v3
    #   with:
    #     repository: fcm-digital/helm-chart-template
    #     token: ${{ inputs.github_token_checkout }}
    #     ref: ${{ inputs.helm_chart_template_branch }}
    #     path: helm-chart-template

    - uses: actions/checkout@v3
      if: (github.ref == 'refs/heads/master') || (github.ref == 'refs/heads/main')
      with:
        repository: fcm-digital/helm-chart-${{ inputs.app_name }}-values
        token: ${{ inputs.github_token_checkout }}
        ref: master
        path: helm-chart-${{ inputs.app_name }}-values

    - uses: actions/checkout@v3
      if: (github.ref != 'refs/heads/master') && (github.ref != 'refs/heads/main')
      with:
        repository: fcm-digital/helm-chart-${{ inputs.app_name }}-values
        token: ${{ inputs.github_token_checkout }}
        ref: staging
        path: helm-chart-${{ inputs.app_name }}-values