---
name: "Login to GAR"
description: "Login to Google Artifact Registry."

inputs:
  artifact_region:
    description: "Region or zone for Google Artifact Registry."
    required: false
    default: "europe"
  gcr_json_password:
    description: "The JSON password for GCR (JSON auth) (Required for JSON auth)"
    required: false
    default: ""
  gcr_wif_access_token_password:
    description: "The access token for GCR. (WIF auth) (Required for WIF auth)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Validate inputs
      run: |
        if [ -z "${{ inputs.gcr_json_password }}" ] && [ -z "${{ inputs.gcr_wif_access_token_password }}" ]; then
          echo "Error: At least one of gcr_json_password or gcr_wif_access_token_password must be provided."
          exit 1
        fi
      shell: bash

    - id: login-gcr-json
      if: inputs.gcr_json_password != ''
      name: Login to Google Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.artifact_region }}-docker.pkg.dev
        username: _json_key
        password: ${{ inputs.gcr_json_password }}

    - id: login-gcr-wif
      if: inputs.gcr_wif_access_token_password != ''
      name: Login to GCR
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.artifact_region }}-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ inputs.gcr_wif_access_token_password }}