---
name: "Login to GAR"
description: "Login to Google Artifact Registry."

inputs:
  gcp_wif_access_token:
    description: "The access token for GAR. (WIF auth)"
    required: true
  artifact_region:
    description: "Region or zone for Google Artifact Registry."
    required: false
    default: "europe"

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - id: login-gar-wif
      name: Login to GAR
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.artifact_region }}-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ inputs.gcp_wif_access_token }}