---
name: 'Kube-Linter'
description: 'Kube Linter Execution for Helm Chart Templates.'

inputs:
  app_name:
    description: 'The application name that will be deployed.'
    required: true
  branch_name:
    description: 'Current branch name.'
    required: true
  env_to_deploy:
    description: >
      Environment where the image will be deployed.
    required: true
  exclude_rules:
    description: 'The kube-linter rules to be excluded.'
    required: false
  image_tag:
    description: 'The image tag that will be deployed.'
    required: true
  go_version:
    description: 'Go Version'
    required: false
    default: '1.20'
  helm_version:
    description: 'Helm Version'
    required: false
    default: 'v3.12.1'

runs:
  using: "composite"
  steps:
    - id: install-go
      name: 'GO Installation'
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go_version }}
        cache: false

    - id: install-helm
      name: 'Helm Installation'
      uses: azure/setup-helm@v3
      with:
        version: ${{ inputs.helm_version }} # Current Helm version installed into ArgoCD Pods.
        # token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'

    - id: install-kube-linter
      name: 'Kube-Linter Installation'
      shell: bash
      run: |
        go version
        go install golang.stackrox.io/kube-linter/cmd/kube-linter@latest

    - id: exec-kube-linter-staging
      name: 'Kube-Linter Execution for Staging'
      if: inputs.branch_name != 'master' && inputs.branch_name != 'main'
      shell: bash
      run: |
        cd helm-chart-template
        helm template . --name-template=${{ inputs.app_name }} --namespace=${{ inputs.env_to_deploy }} \
          --set currentTag=${{ inputs.image_tag }} \
          -f ../kube/values/${{ inputs.app_name }}/staging/values-stg.yaml \
          -f ../kube/values/${{ inputs.app_name }}/staging/${{ inputs.env_to_deploy }}/values-stg.yaml \
          > output-template.yaml
        kube-linter lint output-template.yaml --exclude non-existent-service-account ${{ inputs.exclude_rules }}

    - id: exec-kube-linter-production
      name: 'Kube-Linter Execution for Production'
      if: inputs.env_to_deploy == 'prod' && (inputs.branch_name == 'master' || inputs.branch_name == 'main')
      shell: bash
      run: |
        cd helm-chart-template
        helm template . --name-template=${{ inputs.app_name }} --namespace=prod-namespace \
          --set currentTag=${{ inputs.image_tag }} \
          -f ../kube/values/${{ inputs.app_name }}/prod/values-prod.yaml \
          > output-template.yaml
        kube-linter lint output-template.yaml --exclude non-existent-service-account ${{ inputs.exclude_rules }}