---
name: 'Checkout Local Repository'
description: 'Checkout local repository and init all variables needed for Argocd deployment.'

inputs:
  github_ref_name:
    required: true
    type: string
    description: 'The branch or tag name that triggered the workflow run.'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - run: |
        export COMMIT_TIME=$( git show -s --format=%ct )
        echo "TIME=$( date -d@$COMMIT_TIME -u +"%Y-%m-%dT%H%M")" >> $GITHUB_ENV
        echo "SHORT_SHA=$( git rev-parse --short=7 HEAD )" >> $GITHUB_ENV
        echo "CURRENT_ENV=$( cut -d '-' -f 1 <<< "${{ inputs.github_ref_name }}" )" >> $GITHUB_ENV
        echo "BRANCH_NAME=${{ inputs.github_ref_name }}" >> $GITHUB_ENV
      shell: bash
