---
name: 'Init Environment Vars'
description: 'Init environment variables for ArgoCD deployment.'

runs:
  using: "composite"
  steps:
    - run: |-
        if [[ '${{ github.event_name }}' == 'pull_request' ]]; then
          export BRANCH_NAME_LOCAL=$( env.GITHUB_HEAD_REF )
        elif [[ '${{ github.event_name }}' == 'push' ]]; then
          export BRANCH_NAME_LOCAL=$( env.GITHUB_REF )
        else
          exit 1
        fi
        echo "BRANCH_NAME=$( $BRANCH_NAME_LOCAL )" >> $GITHUB_ENV
        printenv
      # echo "CURRENT_ENV=$( cut -d '-' -f 1 <<< "$BRANCH_NAME_LOCAL" )" >> $GITHUB_ENV
      shell: bash
