---
name: 'GCP Environment ArgoCD'
description: 'Install tools & Configure Google Cloud environment for ArgoCD deployment.'

inputs:
  artifact_region:
    description: 'Region or zone for Google Artifact Registry.'
    required: false
    type: string
    default: 'europe'
  gcp_json:
    description: 'The Service Account that contains the permissions to GCP.'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - id: setup-gcp-credentials
      name: 'Set Up Google Credentials'
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ inputs.gcp_json }}

    - id: login-gcp-artifact
      name: 'Login to Google Artifact Registry'
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.artifact_region }}-docker.pkg.dev
        username: _json_key
        password: ${{ inputs.gcp_json }}