---
name: 'Build Docker image'
description: 'Build a Docker image using default tags'
inputs:
  app_name:
    description: 'Name of the app to deploy.'
    required: true
    type: string
  artifact_region:
    description: 'Region or zone for Google Artifact Registry.'
    required: false
    type: string
    default: 'europe'
  artifact_repository_name:
    description: 'Name of the repo to upload image: ${url}/${repo}/${app}'
    required: false
    type: string
  context:
    description: 'Context to build image (default: ./)'
    required: false
    type: string
    default: './'
  file:
    description: 'Path to Dockerfile'
    required: false
    type: string
    default: 'Dockerfile'
  push:
    description: 'Whether to push image to registry, or build locally.'
    required: false
    type: bool
    default: true

runs:
  using: 'composite'
  steps:
    - run: |-
        export COMMIT_TIME=$( git show -s --format=%ct )
        echo "TIME=$( date -d@$COMMIT_TIME -u +"%Y-%m-%dT%H%M")" >> $GITHUB_ENV
        echo "SHORT_SHA=$( git rev-parse --short=7 HEAD )" >> $GITHUB_ENV
        echo "CURRENT_ENV=$( cut -d '-' -f 1 <<< "${{ github.ref#refs/heads/ }}" )" >> $GITHUB_ENV
        echo "BRANCH_NAME=${{ github.ref#refs/heads/ }}" >> $GITHUB_ENV
        if [[ -z "${{ inputs.artifact_repository_name }}" ]]; then
          echo "REPO_URL=${{ inputs.artifact_region }}-docker.pkg.dev/fcm-platform-artifacts-ceba/${{ inputs.app_name }}/${{ inputs.app_name }}" >> $GITHUB_ENV
        else
          echo "REPO_URL=${{ inputs.artifact_region }}-docker.pkg.dev/fcm-platform-artifacts-ceba/${{ inputs.artifact_repository_name }}/${{ inputs.app_name }}" >> $GITHUB_ENV
        fi

        echo ${{ github.ref }}
      shell: bash

    # - name: "Build & push Docker image [branch tag] + [latest tag]"
    #   uses: docker/build-push-action@v4
    #   if: (github.ref == 'refs/heads/master') || (github.ref == 'refs/heads/main')
    #   with:
    #     push: ${{ inputs.push }}
    #     file: ${{ inputs.file }}
    #     context: ${{ inputs.context }}
    #     tags: |-
    #       ${{ env.REPO_URL }}:${{ env.BRANCH_NAME }}
    #       ${{ env.REPO_URL }}:${{ env.BRANCH_NAME }}-${{ env.TIME }}-${{ env.SHORT_SHA }}
    #       ${{ env.REPO_URL }}:latest

    # - name: "Build & push Docker image [branch tag]"
    #   uses: docker/build-push-action@v4
    #   if: (github.ref != 'refs/heads/master') && (github.ref != 'refs/heads/main')
    #   with:
    #     push: ${{ inputs.push }}
    #     file: ${{ inputs.file }}
    #     context: ${{ inputs.context }}
    #     tags: |-
    #       ${{ env.REPO_URL }}:${{ env.BRANCH_NAME }}
    #       ${{ env.REPO_URL }}:${{ env.BRANCH_NAME }}-${{ env.TIME }}-${{ env.SHORT_SHA }}

