---
name: 'Build Docker image'
description: 'Build a Docker image using default tags.'
inputs:
  file:
    required: false
    type: string
    default: 'Dockerfile'
    description: 'Path to Dockerfile (default: Dockerfile'
  context:
    required: false
    type: string
    default: './'
    description: 'Context to build image (default: ./)'
  app:
    required: true
    type: string
    description: 'Name of the app, to use for the registry'
  region:
    required: false
    default: 'europe-west1'
    type: string
    description: 'Region or zone for Google Artifact Registry (default: europe-west1)'
  push:
    required: false
    default: true
    type: bool
    description: 'Whether to push image to registry, or build locally.'

runs:
  using: 'composite'
  steps:
    - run: |
        export COMMIT_TIME=$(git show -s --format=%ct)
        echo "TIME=$( date -d@$COMMIT_TIME -u +"%Y-%m-%dT%H%M")" >> $GITHUB_ENV
        echo "SHORT_SHA=$( git rev-parse --short=7 HEAD )" >> $GITHUB_ENV
      shell: bash

    - name: "Build & push Docker image [branch tag]"
      uses: docker/build-push-action@v2
      with:
        push: ${{ inputs.push }}
        file: ${{ inputs.file }}
        context: ${{ inputs.context }}
        tags: |
          gcr.io/janus-156310/${{ inputs.app }}:${{ github.ref_name }}
          gcr.io/janus-156310/${{ inputs.app }}:${{ github.ref_name }}-${{ env.TIME }}-${{ env.SHORT_SHA }}
          ${{ inputs.region }}-docker.pkg.dev/fcm-platform-artifacts-ceba/${{ inputs.app }}/${{ inputs.app }}:${{ github.ref_name }}
          ${{ inputs.region }}-docker.pkg.dev/fcm-platform-artifacts-ceba/${{ inputs.app }}/${{ inputs.app }}:${{ github.ref_name }}-${{ env.TIME }}-${{ env.SHORT_SHA }}

    - name: "Build Docker image [latest tag]"
      uses: docker/build-push-action@v2
      with:
        push: false
        file: ${{ inputs.file }}
        context: ${{ inputs.context }}
        tags: |
          ${{ inputs.region }}-docker.pkg.dev/fcm-platform-artifacts-ceba/${{ inputs.app }}/${{ inputs.app }}:latest
          gcr.io/janus-156310/${{ inputs.app }}:latest

    - name: "Build & push Docker image [latest tag]"
      uses: docker/build-push-action@v2
      if: ${{ endsWith(github.ref, '/master') }}
      with:
        push: ${{ inputs.push }}
        file: ${{ inputs.file }}
        context: ${{ inputs.context }}
        tags: |
          ${{ inputs.region }}-docker.pkg.dev/fcm-platform-artifacts-ceba/${{ inputs.app }}/${{ inputs.app }}:latest
          gcr.io/janus-156310/${{ inputs.app }}:latest
