---
name: 'Build Docker image'
description: 'Build a Docker image using default tags'
inputs:
  file:
    required: false
    type: string
    default: 'Dockerfile'
    description: 'Path to Dockerfile'
  context:
    required: false
    type: string
    default: './'
    description: 'Context to build image (default: ./)'
  app:
    required: true
    type: string
    description: 'Name of the app, to use for the registry: ${url}/${repo}/${app}'
  region:
    required: false
    default: 'europe'
    type: string
    description: 'Region or zone for Google Artifact Registry'
  repo:
    required: false
    type: string
    description: 'Name of the repo to upload image: ${url}/${repo}/${app}'
  push:
    required: false
    default: true
    type: bool
    description: 'Whether to push image to registry, or build locally.'

runs:
  using: 'composite'
  steps:
    - run: |-
        export COMMIT_TIME=$(git show -s --format=%ct)
        echo "TIME=$( date -d@$COMMIT_TIME -u +"%Y-%m-%dT%H%M")" >> $GITHUB_ENV
        echo "SHORT_SHA=$( git rev-parse --short=7 HEAD )" >> $GITHUB_ENV
        if [[ -z "${{ inputs.repo }}" ]]; then
          echo "REPO_URL=${{ inputs.region }}-docker.pkg.dev/fcm-platform-artifacts-ceba/${{ inputs.app }}/${{ inputs.app }}" >> $GITHUB_ENV
        else
          echo "REPO_URL=${{ inputs.region }}-docker.pkg.dev/fcm-platform-artifacts-ceba/${{ inputs.repo }}/${{ inputs.app }}" >> $GITHUB_ENV
        fi
      shell: bash

    - name: "Build & push Docker image [branch tag]"
      uses: docker/build-push-action@v6
      with:
        push: ${{ inputs.push }}
        file: ${{ inputs.file }}
        context: ${{ inputs.context }}
        tags: |-
          ${{ env.REPO_URL }}:${{ github.ref_name }}
          ${{ env.REPO_URL }}:${{ github.ref_name }}-${{ env.TIME }}-${{ env.SHORT_SHA }}

    - name: "Build Docker image [latest tag]"
      uses: docker/build-push-action@v6
      with:
        push: false
        file: ${{ inputs.file }}
        context: ${{ inputs.context }}
        tags: |-
          ${{ env.REPO_URL }}:latest

    - name: "Build & push Docker image [latest tag]"
      uses: docker/build-push-action@v6
      if: ${{ endsWith(github.ref, '/master') || endsWith(github.ref, '/main' }}
      with:
        push: ${{ inputs.push }}
        file: ${{ inputs.file }}
        context: ${{ inputs.context }}
        tags: |-
          ${{ env.REPO_URL }}:latest
