---
name: "Export Docker image"
description: "Export a Docker image as an Artifact object to be retrieved from another job."
inputs:
  file:
    required: false
    type: string
    default: "Dockerfile"
    description: "Path to Dockerfile (default: Dockerfile"
  context:
    required: false
    type: string
    default: "./"
    description: "Context to build image (default: ./)"
  app:
    required: true
    type: string
    description: "Name of the app, to use for the registry"
  region:
    required: false
    default: "europe-west1"
    type: string
    description: "Region or zone for Google Artifact Registry (default: europe-west1)"

runs:
  using: "composite"
  steps:
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        file: ${{ inputs.file }}
        context: ${{ inputs.context }}
        tags: |
          gcr.io/janus-156310/${{ inputs.app }}:${{ github.ref_name }}
          gcr.io/janus-156310/${{ inputs.app }}:${{ github.ref_name }}-${{ env.TIME }}-${{ env.SHORT_SHA }}
          gcr.io/janus-156310/${{ inputs.app }}:latest
          ${{ inputs.region }}-docker.pkg.dev/fcm-platform-artifacts-ceba/${{ inputs.app }}/${{ inputs.app }}:${{ github.ref_name }}
          ${{ inputs.region }}-docker.pkg.dev/fcm-platform-artifacts-ceba/${{ inputs.app }}/${{ inputs.app }}:${{ github.ref_name }}-${{ env.TIME }}-${{ env.SHORT_SHA }}
          ${{ inputs.region }}-docker.pkg.dev/fcm-platform-artifacts-ceba/${{ inputs.app }}/${{ inputs.app }}:latest
        outputs: type=docker,dest=/tmp/${{ inputs.app }}.tar

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.app }}
        path: /tmp/${{ inputs.app }}.tar
        retention-days: 1
