---
name: 'Ask for Manual Approval'
description: 'Ask for Manual Approval'

inputs:
  app_name:
    description: 'Name of the app to deploy.'
    required: true
  app_region:
    description: 'Region of the app to deploy.'
    required: true
  approvers:
    description: 'The GitHub token to checkout helm_chart_template repository.'
    required: true
  env_to_deploy:
    description: 'Environment where the image will be deployed.'
    required: true
  app_id:
    description: 'Manual Approvals GitHub App AppId.'
    required: true
  private_key:
    description: 'Manual Approvals GitHub App Private Key.'
    required: true

runs:
  using: 'composite'
  steps:
    - id: argocd-url
      name: ArgoCD URL
      run: |
        if [[ "${{ inputs.branch_name }}" == "prod" ]]; then
          echo "ARGOCD_URL=$( echo "https://argocd.fcm.digital/applications/argocd/${{ inputs.app_name }}-prod-${{ inputs.app_region }}" )" >> $GITHUB_ENV
        else
          echo "ARGOCD_URL=$( echo "https://argocd.fcm.digital/applications/argocd/${{ inputs.app_name }}-${{ inputs.env_to_deploy }}-stg-${{ inputs.app_region }}" )" >> $GITHUB_ENV
        fi
      shell: bash

    - id: generate-app-token
      name: Generate App Token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ inputs.app_id }}
        private_key: ${{ inputs.private_key }}

    - id: manual-approval
      name: Ask for Manual Approval
      uses: trstringer/manual-approval@v1
      with:
        minimum-approvals: 1
        secret: ${{ steps.generate-app-token.outputs.token }}
        approvers: ${{ inputs.approvers }}
        issue-title: "Deploying to Production."
        issue-body: "Please 'approve' or 'deny' the deployment of new app version.\nTake a look to: ${{ env.ARGOCD_URL }}" #ToDo: Parametrize