---
name: 'Ask for Manual Approval'
description: 'Ask for Manual Approval'

runs:
  using: 'composite'
  steps:
    
    - uses: trstringer/manual-approval@v1
      with:
        minimum-approvals: 1
        issue-title: "Deploying to Production."
        issue-body: "Please approve or deny the deployment of new app version."