---
name: 'ArgoCD CLI Delete Resources'
description: 'ArgoCD CLI commands for Resources deletion.'

inputs:
  app_name:
    description: 'Name of the app to deploy.'
    required: true
  app_region:
    description: 'Region of the app to deploy.'
    required: true
  argocd_auth_token:
    description: 'ArgoCD auth token with get/sync permissions over apps.'
    required: true
  argocd_url:
    description: 'ArgoCD URL (default: argocd.fcm.digital).'
    required: false
    default: 'argocd.fcm.digital'
  branch_name:
    description: 'Current branch name.'
    required: true
  env_to_deploy:
    description: 'Environment where the image will be deployed.'
    required: true
  resources:
    description: 'Resources type_name to be deleted.'
    required: false

runs:
  using: "composite"
  steps:
    - id: argocd-cli-delele-resources
      if: inputs.resources
      name: 'ArgoCD CLI Delete Resources'
      shell: bash
      run: ${{ github.action_path }}/delete_resources_entrypoint.sh
      env:
        APP_NAME: ${{ inputs.app_name }}
        APP_REGION: ${{ inputs.app_region }}
        ARGOCD_AUTH_TOKEN: ${{ inputs.argocd_auth_token }}
        ARGOCD_URL: ${{ inputs.argocd_url }}
        BRANCH_NAME: ${{ inputs.branch_name }}
        ENV_TO_DEPLOY: ${{ inputs.env_to_deploy }}
        RESOURCES: ${{ inputs.resources }}