---
name: 'Slack-Changelog'
description: 'Send Notifications Changelog to Slack Channel.'

inputs:
  app_name:
    description: 'The application name.'
    required: true
  app_region:
    description: 'Region of the app to deploy.'
    required: true
  argocd_auth_token:
    description: 'ArgoCD auth token with get/sync permissions over apps.'
    required: true
  argocd_url:
    description: 'ArgoCD URL (default: argocd.fcm.digital).'
    required: false
    default: 'argocd.fcm.digital'
  env_to_deploy:
    description: 'Environment where the image will be deployed.'
    required: true
  image_tag:
    description: 'The new commit to compare with the old one.'
    required: true
  slack_channel:
    description: 'The Slack channel to where the Changelog notification will be sent.'
    required: false
    default: "notifications-testing" #! Test value
  slack_bot_token:
    description: 'The Slack token with the proper permissions.'
    required: true

outputs:
  branch_name:
    description: 'The current Branch name.'
    value: ${{ steps.get-live-commit-id.outputs.live_image_tag }}

runs:
  using: "composite"
  steps:
  - name: Get live Commit Id
    id: get-live-commit-id
    shell: bash
    run: ${{ github.action_path }}/entrypoint.sh
    env:
      APP_NAME: ${{ inputs.app_name }}
      APP_REGION: ${{ inputs.app_region }}
      ARGOCD_AUTH_TOKEN: ${{ inputs.argocd_auth_token }}
      ARGOCD_URL: ${{ inputs.argocd_url }}
      BRANCH_NAME: ${{ inputs.branch_name }}
      ENV_TO_DEPLOY: ${{ inputs.env_to_deploy }}
      
  - name: Send Changelog to Slack
    id: slack
    uses: slackapi/slack-github-action@v1
    with:
      channel-id: ${{ inputs.slack_channel }}
      slack-message: "A new release has been deployed in Production: https://github.com/fcm-digital/${{ inputs.app_name }}/compare/${{ steps.get-live-commit-id.outputs.live_image_tag }}...${{ inputs.image_tag }}"
    env:
      SLACK_BOT_TOKEN: ${{ inputs.slack_bot_token }}