---
name: 'Slack-Changelog'
description: 'Send Notifications Changelog to Slack Channel.'

inputs:
  app_name:
    description: 'The application name.'
    required: true
  app_region:
    description: 'Region of the app to deploy.'
    required: true
  argocd_auth_token:
    description: 'ArgoCD auth token with get/sync permissions over apps.'
    required: true
  argocd_url:
    description: 'ArgoCD URL (default: argocd.fcm.digital).'
    required: false
    default: 'argocd.fcm.digital'
  env_to_deploy:
    description: 'Environment where the image will be deployed.'
    required: true
  image_tag:
    description: 'The new commit to compare with the old one.'
    required: true
  slack_channel:
    description: 'The Slack channel to where the Changelog notification will be sent.'
    required: false
    default: "notifications-testing" #! Test value
  slack_bot_token:
    description: 'The Slack token with the proper permissions.'
    required: true

outputs:
  live_image_tag:
    description: 'The current Branch name.'
    value: ${{ steps.get-live-commit-id.outputs.live_image_tag }}
  new_commit_id:
    description: 'The new Commit Id.'
    value: ${{ steps.format-commit-ids.outputs.new_commit_id }}
  live_commit_id:
    description: 'The live/current Commit Id.'
    value: ${{ steps.format-commit-ids.outputs.live_commit_id }}

runs:
  using: "composite"
  steps:
  - name: Get live Image Tag
    id: get-live-image-tag
    shell: bash
    run: ${{ github.action_path }}/entrypoint.sh
    env:
      APP_NAME: ${{ inputs.app_name }}
      APP_REGION: ${{ inputs.app_region }}
      ARGOCD_AUTH_TOKEN: ${{ inputs.argocd_auth_token }}
      ARGOCD_URL: ${{ inputs.argocd_url }}
      ENV_TO_DEPLOY: ${{ inputs.env_to_deploy }}

  - name: Format Image Tags to get Commit IDs
    id: format-commit-ids
    shell: bash
    run: |
      echo "new_commit_id=$( echo "${{ inputs.image_tag }}" | awk -F '-' '{print $NF}' )" >> $GITHUB_OUTPUT
      echo "live_commit_id=$( echo "${{ steps.get-live-commit-id.outputs.live_image_tag }}" | awk -F '-' '{print $NF}' )" >> $GITHUB_OUTPUT

  - name: Send Changelog to Slack
    id: slack
    uses: slackapi/slack-github-action@v1
    with:
      channel-id: ${{ inputs.slack_channel }}
      slack-message: "A new release has been deployed in Production: https://github.com/fcm-digital/${{ inputs.app_name }}/compare/${{ steps.format-commit-ids.outputs.live_commit_id }}...${{ steps.format-commit-ids.outputs.new_commit_id }}"
    env:
      SLACK_BOT_TOKEN: ${{ inputs.slack_bot_token }}