---
name: 'Slack-Changelog'
description: 'Send Notifications Changelog to Slack Channel.'

inputs:
  app_name:
    description: 'The application name.'
    required: true
  image_tag:
    description: 'The new commit to compare with the old one.'
    required: true
  live_image_tag:
    description: 'The live/current commit to compare with the new one.'
    required: true        
  release_content:
    description: 'Release content to display in the Slack message.'
    required: false
  slack_channel:
    description: 'The Slack channel to where the Changelog notification will be sent.'
    required: false
    default: "notifications-testing" #! Test value
  slack_bot_token:
    description: 'The Slack token with the proper permissions.'
    required: true

outputs:
  new_commit_id:
    description: 'The new Commit Id.'
    value: ${{ steps.format-commit-ids.outputs.new_commit_id }}
  live_commit_id:
    description: 'The live/current Commit Id.'
    value: ${{ steps.format-commit-ids.outputs.live_commit_id }}

runs:
  using: "composite"
  steps:
  - name: Format Image Tags to get Commit IDs
    id: format-commit-ids
    shell: bash
    run: |
      echo "new_commit_id=$( echo "${{ inputs.image_tag }}" | awk -F '-' '{print $NF}' )" >> $GITHUB_OUTPUT
      echo "live_commit_id=$( echo "${{ inputs.live_image_tag }}" | awk -F '-' '{print $NF}' )" >> $GITHUB_OUTPUT

  - name: Send Changelog to Slack
    id: slack
    uses: slackapi/slack-github-action@v1
    with:
      channel-id: ${{ inputs.slack_channel }}
      slack-message: "*Hey <!here>. A new release has been deployed in Production:* \n
                      - :git-deploy: App Name: ${{ inputs.app_name }}
                      - :git-package: Release Content: ${{ inputs.release_content }} \n
                      *Technical information:* \n
                      - :git-tag: New Image: ${{ inputs.image_tag }} \n
                      - :git-compare: Code Diff: https://github.com/fcm-digital/${{ inputs.app_name }}/compare/${{ steps.format-commit-ids.outputs.live_commit_id }}...${{ steps.format-commit-ids.outputs.new_commit_id }}"
    env:
      SLACK_BOT_TOKEN: ${{ inputs.slack_bot_token }}