---
name: 'Checkout App Values Repository'
description: 'Checkout app values repository (helm-chart-app-values) for ArgoCD deployment.'

inputs:
  app_name:
    description: 'Name of the app to deploy.'
    required: true
  github_token_checkout:
    description: 'The GitHub token to checkout helm_chart_template repository.'
    required: true
  branch_name:
    description: 'Target Branch from where the values will be synced.'
    required: true
  env_to_deploy:
    description: 'Target Environment: prod, sandbox...'
    required: true
  image_tag:
    description: 'Specific Image Tag to Deploy.'
    required: true

outputs:
  env_to_deploy:
    description: 'The current Environment name.'
    value: ${{ steps.init-context-vars.outputs.env_to_deploy }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch_name }}

    - id: init-context-vars
      run: |
        if [[ ${{ inputs.env_to_deploy == 'master'  }} || ${{ inputs.env_to_deploy == 'main'  }} ]]; then
          echo "env_to_deploy=prod" >> $GITHUB_OUTPUT
        else
          echo "env_to_deploy=$( echo ${{ inputs.env_to_deploy }} )" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - uses: actions/checkout@v3
      if: steps.init-context-vars.outputs.env_to_deploy == 'prod'
      with:
        repository: fcm-digital/helm-chart-${{ inputs.app_name }}-values
        token: ${{ inputs.github_token_checkout }}
        ref: master
        path: helm-chart-${{ inputs.app_name }}-values-prod

    - uses: actions/checkout@v3
      with:
        repository: fcm-digital/helm-chart-${{ inputs.app_name }}-values
        token: ${{ inputs.github_token_checkout }}
        ref: staging
        path: helm-chart-${{ inputs.app_name }}-values-staging
