---
name: 'Checkout App Values Repository'
description: 'Checkout app values repository (helm-chart-app-values) for ArgoCD deployment.'

inputs:
  app_name:
    description: 'Name of the app to deploy.'
    required: true
  github_token_checkout:
    description: 'The GitHub token to checkout helm_chart_template repository.'
    required: true
  branch_name:
    description: 'Target Branch from where the values will be synced.'
    required: true
  env_to_deploy:
    description: 'Target Environment: prod, sandbox...'
    required: true
  create_image:
    description: 'Create a new image tag.'
    required: false
    default: "false"

outputs:
  env_to_deploy:
    description: 'The environment to deploy on.'
    value: ${{ steps.init-context-vars.outputs.env_to_deploy }}
  image_tag:
    description: 'The new Image Tag that will be built.'
    value: ${{ steps.init-image-tag.outputs.image_tag }}
  commit:
    description: 'The commit Id.'
    value: ${{ steps.init-context-vars.outputs.short_sha }}
  workflow_at:
    description: 'The time where the workflow was executed.'
    value: ${{ steps.init-context-vars.outputs.current_time }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch_name }}

    - id: init-context-vars
      run: |
        if [[ '${{ github.event_name }}' == 'workflow_dispatch' ]]; then
          echo "env_to_deploy=$( echo ${{ inputs.env_to_deploy }} )" >> $GITHUB_OUTPUT

          if [[ "${{ inputs.create_image }}" == "true" ]]; then
            echo "current_time=$( date -u +"%Y-%m-%dT%H%M" )" >> $GITHUB_OUTPUT
            echo "short_sha=$( git rev-parse --short=7 HEAD )" >> $GITHUB_OUTPUT
          else
            echo "current_time=NO_TIME" >> $GITHUB_OUTPUT
            echo "short_sha=NO_SHA" >> $GITHUB_OUTPUT
          fi
        else
          exit 1
        fi
      shell: bash

    - id: init-image-tag
      run: |
        if [[ "${{ inputs.create_image }}" == "true" ]]; then
          echo "image_tag=$( echo ${{ inputs.branch_name }}-${{ steps.init-context-vars.outputs.current_time }}-${{ steps.init-context-vars.outputs.short_sha }} )" >> $GITHUB_OUTPUT
        else
          echo "image_tag=NO_TAG_BUILT" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - uses: actions/checkout@v4
      if: steps.init-context-vars.outputs.env_to_deploy == 'prod' &&
          (inputs.branch_name == 'master' || inputs.branch_name == 'main')
      with:
        repository: fcm-digital/helm-chart-${{ inputs.app_name }}-values
        token: ${{ inputs.github_token_checkout }}
        ref: master
        path: helm-chart-${{ inputs.app_name }}-values-prod

    - uses: actions/checkout@v4
      with:
        repository: fcm-digital/helm-chart-${{ inputs.app_name }}-values
        token: ${{ inputs.github_token_checkout }}
        ref: staging
        path: helm-chart-${{ inputs.app_name }}-values-staging
