---
name: "Login to GKE"
description: "Login to Google Kubernetes Engine cluster."

inputs:
  gcp_json:
    description: "The Service Account that contains the permissions to GKE. (Required for JSON auth)"
    required: false
  gcp_wif_project_id:
    description: "The GCP project ID to use for WIF authentication."
    required: false
  gcp_wif_pool:
    description: "The GCP WIF Pool to use for authentication."
    required: false
  gcp_wif_provider:
    description: "The GCP WIF Provider to use for authentication."
    required: false
  gcp_wif_service_account:
    description: "The GCP SA to use for authentication."
    required: false

  cluster_name:
    description: "The name of the GKE cluster."
    required: true
    default: "fcm-platform-stg-euw1"
  location:
    description: "The location of the GKE cluster."
    required: true
    default: "europe-west1"

runs:
  using: "composite"
  steps:
    - id: auth-gcp
      name: Authenticate to GCP
      uses: ./.github/actions/google-cloud-platform/auth
      with:
        gcp_json: ${{ inputs.gcp_json }}
        gcp_wif_project_id: ${{ inputs.gcp_wif_project_id }}
        gcp_wif_pool: ${{ inputs.gcp_wif_pool }}
        gcp_wif_provider: ${{ inputs.gcp_wif_provider }}
        gcp_wif_service_account: ${{ inputs.gcp_wif_service_account }}

    - name: Set up Cloud SDK
      uses: "google-github-actions/setup-gcloud@v3"
      with:
        install_components: "gke-gcloud-auth-plugin"

    - id: get-gke-credentials
      name: Get GKE Credentials
      uses: "google-github-actions/get-gke-credentials@v2"
      with:
        cluster_name: ${{ inputs.cluster_name }}
        location: ${{ inputs.location }}

    - id: print-kubectl-version
      name: Print kubectl version
      run: |
        kubectl version
      shell: bash