---
name: "Login to GKE"
description: "Login to Google Kubernetes Engine cluster."

inputs:
  auth_gcp:
    description: "Enable GCP authentication."
    required: false
    default: "true"
  gcp_wif_project_id:
    description: "The GCP project ID to use for WIF authentication. (Required if auth_gcp is true)"
    required: false
  gcp_wif_pool:
    description: "The GCP WIF Pool to use for authentication. (Required if auth_gcp is true)"
    required: false
  gcp_wif_provider:
    description: "The GCP WIF Provider to use for authentication. (Required if auth_gcp is true)"
    required: false
  gcp_wif_service_account:
    description: "The GCP SA to use for authentication. (Required if auth_gcp is true)"
    required: false

  gke_cluster_name:
    description: "The name of the GKE cluster."
    required: false
  gke_location:
    description: "The location of the GKE cluster."
    required: false

runs:
  using: "composite"
  steps:
    - id: auth-gcp
      if: inputs.auth_gcp == 'true'
      name: Authenticate to GCP
      uses: ./.github/actions/google-cloud-platform/auth
      with:
        setup_gcloud_sdk: True
        gcp_wif_project_id: ${{ inputs.gcp_wif_project_id }}
        gcp_wif_pool: ${{ inputs.gcp_wif_pool }}
        gcp_wif_provider: ${{ inputs.gcp_wif_provider }}
        gcp_wif_service_account: ${{ inputs.gcp_wif_service_account }}

    - id: get-gke-credentials
      if: inputs.gke_cluster_name != '' && inputs.gke_location != ''
      name: Get GKE Credentials
      uses: "google-github-actions/get-gke-credentials@v2"
      with:
        cluster_name: ${{ inputs.gke_cluster_name }}
        location: ${{ inputs.gke_location }}

    - id: print-kubectl-version
      name: Print kubectl version
      run: |
        kubectl version
      shell: bash