---
name: "Login to GKE"
description: "Login to Google Kubernetes Engine cluster."

inputs:
  gke_cluster_name:
    description: "The name of the GKE cluster."
    required: false
  gke_location:
    description: "The location of the GKE cluster."
    required: false

runs:
  using: "composite"
  steps:
    - id: get-gke-credentials
      if: inputs.gke_cluster_name != '' && inputs.gke_location != ''
      name: Get GKE Credentials
      uses: "google-github-actions/get-gke-credentials@v2"
      with:
        cluster_name: ${{ inputs.gke_cluster_name }}
        location: ${{ inputs.gke_location }}

    - id: print-kubectl-version
      name: Print kubectl version
      run: |
        kubectl version
      shell: bash
