---
name: "Init Deployment Context"
description: "Resolve and validate branch_name and env_to_deploy for ArgoCD deployment flows."

inputs:
  branch_name:
    description: "Branch Name to deploy (required for workflow_dispatch/workflow_run)."
    required: false
  env_to_deploy:
    description: "Target environment to deploy (required for workflow_dispatch)."
    required: false

outputs:
  branch_name:
    description: "The resolved branch name."
    value: ${{ steps.init-context.outputs.branch_name }}
  env_to_deploy:
    description: "The resolved target environment."
    value: ${{ steps.init-context.outputs.env_to_deploy }}

runs:
  using: "composite"
  steps:
    - id: init-context
      name: Init deployment context
      run: |
        set -euo pipefail

        EVENT_NAME="${{ github.event_name }}"
        BRANCH_NAME=""
        ENV_TO_DEPLOY=""

        if [[ "$EVENT_NAME" == "workflow_dispatch" ]] || [[ "$EVENT_NAME" == "workflow_run" ]]; then
          if [[ -z "${{ inputs.branch_name }}" ]]; then
            echo "# 🚨 Context initialization failed" > "$GITHUB_STEP_SUMMARY"
            echo "## Reason" >> "$GITHUB_STEP_SUMMARY"
            echo "Branch name not provided in a ${EVENT_NAME} event." >> "$GITHUB_STEP_SUMMARY"
            exit 1
          fi

          BRANCH_NAME="${{ inputs.branch_name }}"
          ENV_TO_DEPLOY="${{ inputs.env_to_deploy }}"

          if [[ "$EVENT_NAME" == "workflow_dispatch" ]] && [[ -z "$ENV_TO_DEPLOY" ]]; then
            echo "# 🚨 Context initialization failed" > "$GITHUB_STEP_SUMMARY"
            echo "## Reason" >> "$GITHUB_STEP_SUMMARY"
            echo "Environment not provided in a workflow_dispatch event." >> "$GITHUB_STEP_SUMMARY"
            exit 1
          fi
        elif [[ "$EVENT_NAME" == "pull_request" ]]; then
          BRANCH_NAME="${{ github.head_ref }}"
          ENV_TO_DEPLOY="NOT_DEFINED"

          echo "The env_to_deploy extraction from branch_name in a PR event is no longer available."
          echo "Use argocd-get-env-to-deploy-on to resolve env_to_deploy."
        elif [[ "$EVENT_NAME" == "push" ]]; then
          BRANCH_NAME="${{ github.ref_name }}"

          if [[ "${{ github.ref }}" == "refs/heads/master" ]] || [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            ENV_TO_DEPLOY="prod"
          else
            ENV_TO_DEPLOY="${{ github.ref_name }}"
          fi
        else
          echo "# 🚨 Context initialization failed" > "$GITHUB_STEP_SUMMARY"
          echo "## Reason" >> "$GITHUB_STEP_SUMMARY"
          echo "Event ${EVENT_NAME} not supported." >> "$GITHUB_STEP_SUMMARY"
          exit 1
        fi

        echo "branch_name=${BRANCH_NAME}" >> "$GITHUB_OUTPUT"
        echo "env_to_deploy=${ENV_TO_DEPLOY}" >> "$GITHUB_OUTPUT"
      shell: bash
