---
name: "Authenticate to GCP via WIF"
description: "GCP auth via WIF"

inputs:
  gcp_wif_project_id:
    description: "The GCP project ID to use for WIF authentication."
    required: false
    default: "874800047694" #seed-5ee1 project
  gcp_wif_pool:
    description: "The GCP WIF Pool to use for authentication."
    required: false
    default: "github-actions"
  gcp_wif_provider:
    description: "The GCP WIF Provider to use for authentication."
    required: false
    default: "github-actions"
  gcp_wif_service_account:
    description: "The GCP SA to use for authentication."
    required: false
    default: "github-actions@seed-5ee1.iam.gserviceaccount.com"
  artifact_region:
    description: "Region or zone for Google Artifact Registry."
    required: false
    default: "europe"

runs:
  using: "composite"
  steps:
    - id: auth-gcp-wif
      name: Authenticate to GCP via WIF
      uses: google-github-actions/auth@v2
      with:
        token_format: "access_token"
        workload_identity_provider: "projects/${{ inputs.gcp_wif_project_id }}/locations/global/workloadIdentityPools/${{ inputs.gcp_wif_pool }}/providers/${{ inputs.gcp_wif_provider }}"
        service_account: ${{ inputs.gcp_wif_service_account }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - id: login-gcp-artifact
      name: "Login to Google Artifact Registry"
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.artifact_region }}-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth-gcp-wif.outputs.access_token }}
