---
name: ""
description: "Configure GCP WIF"

inputs:
  gcp_wif_project_id:
    description: "The GCP project ID to use for WIF authentication."
    required: false
    default: "874800047694" #seed-5ee1 project
  gcp_wif_pool:
    description: "The GCP WIF Pool to use for authentication."
    required: false
    default: "github-actions"
  gcp_wif_provider:
    description: "The GCP WIF Provider to use for authentication."
    required: false
    default: "github-actions"
  gcp_wif_service_account:
    description: "The GCP SA to use for authentication."
    required: false
    default: "github-actions@seed-5ee1.iam.gserviceaccount.com"

runs:
  using: "composite"
  steps:
    - id: auth-gcp-with
      name: Authenticate to GCP via WIF
      uses: google-github-actions/auth@v2
      with:
        token_format: "access_token"
        workload_identity_provider: "projects/${{ inputs.gcp_wif_project_id }}/locations/global/workloadIdentityPools/${{ inputs.gcp_wif_pool }}/providers/${{ inputs.gcp_wif_provider }}"
        service_account: ${{ inputs.gcp_wif_service_account }}
