---
name: 'Helm Template'
description: 'Kube Linter Execution for Helm Chart Templates.'

inputs:
  app_name:
    description: 'The application name.'
    required: true
  environment:
    description: 'Environment where the jobs will be executed.'
    required: true
  image_tag:
    description: 'The image tag that will be used.'
    required: true
  helm_chart_template_version:
    description: 'Helm Chart Template Version'
    required: true
  helm_version:
    description: 'Helm Version'
    required: false
    default: 'v3.15.4'
  workflow_name:
    description: 'Workflow File Name'
    required: false

runs:
  using: "composite"
  steps:
    - id: checkout-helm-chart-values
      if: inputs.environment != 'prod'
      name: Checkout helm-chart-values repository
      uses: actions/checkout@v4
      with:
        repository: fcm-digital/helm-chart-${{ inputs.app_name }}-values
        ref: staging
        path: helm-chart-values

    - id: checkout-helm-chart-template
      name: Checkout helm-chart-template repository
      uses: actions/checkout@v4
      with:
        repository: fcm-digital/helm-chart-template
        ref: ${{ inputs.helm_chart_template_version }}
        path: helm-chart-template

    - id: install-helm
      name: Helm Installation
      uses: azure/setup-helm@v3
      with:
        version: ${{ inputs.helm_version }}

    - id: helm-template-jobs
      if: inputs.environment != 'prod' && inputs.workflow_name != null
      name: Helm Template for Job Resources
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        APP_NAME: ${{ inputs.app_name }}
        ENVIRONMENT: ${{ inputs.environment }}
        IMAGE_TAG: ${{ inputs.image_tag }}
        WORKFLOW_NAME: ${{ inputs.workflow_name }}
      shell: bash

    - id: helm-template-argo-workflows
      if: steps.helm-template-jobs.outcome == 'success' && inputs.environment != 'prod' && inputs.workflow_name != null
      name: Helm Template for Argo Workflows
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        APP_NAME: ${{ inputs.app_name }}
        ENVIRONMENT: ${{ inputs.environment }}
        IMAGE_TAG: ${{ inputs.image_tag }}
        WORKFLOW_NAME: ${{ inputs.workflow_name }}
      shell: bash