---
name: 'Update local values'
description: 'Update current_tag value locally and commit changes.'

inputs:
  app_name:
    required: true
    type: string
    description: >
      The application name that will be deployed.
      The allowed values are:
      - front
      - storybook
      - bigbrother
      - bff
      - itinerarycore
  deployment_type:
    required: True
    type: string
    description: >
      It can take two values:
      - local: update the local repository values
      - remote: sync the helm-chart-template values
  env_to_deploy:
    required: true
    type: string
    description: >
      Environment where the Image will be deployed.
      If it value is 'ALL_ENV', then all environments will be updated with
      the new image deployed in the current environment.
  image_tag:
    required: true
    type: string
    description: 'The image tag that will be deployed.'

runs:
  using: "composite"
  steps:
    - id: local-values-update
      name: Local Values Update (current_tag)
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        APP_NAME: ${{ inputs.app_name }}
        DEPLOYMENT_TYPE: local
        ENV_TO_DEPLOY: ${{ inputs.env_to_deploy }}
        IMAGE_TAG: ${{ inputs.image_tag }}
      shell: bash

    - id: remote-values-sync
      name: Sync Remote Values with Local Values
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        APP_NAME: ${{ inputs.app_name }}
        DEPLOYMENT_TYPE: remote
        ENV_TO_DEPLOY: ${{ inputs.env_to_deploy }}
        IMAGE_TAG: ${{ inputs.image_tag }}
      shell: bash
