---
name: 'Update local values'
description: 'Update current_tag value locally and commit changes.'

inputs:
  app_name:
    description: 'The application name that will be deployed.'
    required: true
  branch_name:
    description: 'Current branch name.'
    required: true
  deploy_on_sandbox:
    description: 'If "true" the deployment in the ALL_ENV stage will be done on the sandbox environment.'
    required: false
    default: 'true'
  env_to_deploy:
    description: >
      Environment where the image will be deployed.
      If the value is 'ALL_ENV', then all environments will be updated.
      If the value is 'ONLY_COMMON_STG_VALUES', then the action will only update the common staging values.
    required: true
  image_tag:
    description: 'The image tag that will be deployed.'
    required: false
  manual:
    description: 'If true, the commit message will specify that is a Manual deployment.'
    required: false
  rollout:
    description: 'If true, the commit message will specify that is a Rollout.'
    required: false
  synced_envs_as_outputs:
    description: 'If true, the action will output the environments that were sycned.'
    required: false
    default: 'false'
  update_deployed_at:
    description: 'If "true" the env DEPLOYED_AT will be updated with the current deployment date.'
    required: false
    default: 'false'
  release_version:
    description: 'The release version that will be deployed.'
    required: false

outputs:
  old_image_tag:
    description: 'The old Branch name.'
    value: ${{ steps.remote-values-sync.outputs.old_image_tag }}
  synced_staging_envs:
    description: 'The synced staging environments.'
    value: ${{ steps.remote-values-sync.outputs.synced_staging_envs }}

runs:
  using: "composite"
  steps:
    - id: remote-values-sync
      name: Sync Remote Values with Local Values
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        APP_NAME: ${{ inputs.app_name }}
        BRANCH_NAME: ${{ inputs.branch_name }}
        DEPLOY_ON_SANDBOX: ${{ inputs.deploy_on_sandbox }}
        ENV_TO_DEPLOY: ${{ inputs.env_to_deploy }}
        IMAGE_TAG: ${{ inputs.image_tag }}
        MANUAL: ${{ inputs.manual }}
        ROLLOUT: ${{ inputs.rollout }}
        SYNCED_ENVS_AS_OUTPUTS: ${{ inputs.synced_envs_as_outputs }}
        UPDATE_DEPLOYED_AT: ${{ inputs.update_deployed_at }}
        RELEASE_VERSION: ${{ inputs.release_version }}
      shell: bash
