---
name: "Update local values"
description: "Update the `current_tag` value in local configuration files and commit the changes to the repository."

inputs:
  app_name:
    description: "The name of the application to be deployed."
    required: true
  branch_name:
    description: "The name of the current Git branch."
    required: true
  deploy_on_performance:
    description: 'Determines if the deployment in the ALL_ENV stage should occur in the performance environment. Defaults to "false".'
    required: false
    default: "false"
  deploy_on_sandbox:
    description: 'Determines if the deployment in the ALL_ENV stage should occur in the sandbox environment. Defaults to "true".'
    required: false
    default: "true"
  env_to_deploy:
    description: >
      Specifies the target environment for image deployment.
      - '<env>': Updates the <env> staging environment.
      - 'prod': Updates the production environment.
      - 'ALL_ENV': Updates all staging environments.
      - 'ONLY_COMMON_STG_VALUES': Updates only the common staging values.
    required: true
  image_tag:
    description: "The specific image tag to be deployed."
    required: false
  manual:
    description: "If set to true, the commit message will indicate a Manual deployment."
    required: false
  rollout:
    description: "If set to true, the commit message will indicate a Rollout."
    required: false
  synced_envs_as_outputs:
    description: 'If set to true, the action will output the environments that were synchronized. Defaults to "false".'
    required: false
    default: "false"
  update_deployed_at:
    description: 'If set to "true", updates the DEPLOYED_AT environment variable with the current deployment date. Defaults to "false".'
    required: false
    default: "false"
  release_version:
    description: 'The version of the release to be deployed. Required when deploying to "prod" when branch is not "master" or "main".'
    required: false

outputs:
  old_image_tag:
    description: "The image tag used in the previous deployment. Required for a potencial Rollback."
    value: ${{ steps.remote-values-sync.outputs.old_image_tag }}
  synced_staging_envs:
    description: "The list of staging environments that were synchronized."
    value: ${{ steps.remote-values-sync.outputs.synced_staging_envs }}ยก

runs:
  using: "composite"
  steps:
    - id: remote-values-sync
      name: Sync Remote Values with Local Values
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        APP_NAME: ${{ inputs.app_name }}
        BRANCH_NAME: ${{ inputs.branch_name }}
        DEPLOY_ON_PERFORMANCE: ${{ inputs.deploy_on_performance }}
        DEPLOY_ON_SANDBOX: ${{ inputs.deploy_on_sandbox }}
        ENV_TO_DEPLOY: ${{ inputs.env_to_deploy }}
        IMAGE_TAG: ${{ inputs.image_tag }}
        MANUAL: ${{ inputs.manual }}
        ROLLOUT: ${{ inputs.rollout }}
        SYNCED_ENVS_AS_OUTPUTS: ${{ inputs.synced_envs_as_outputs }}
        UPDATE_DEPLOYED_AT: ${{ inputs.update_deployed_at }}
        RELEASE_VERSION: ${{ inputs.release_version }}
      shell: bash
