---
name: 'Update local values'
description: 'Update current_tag value locally and commit changes.'

inputs:
  app_name:
    description: 'The name of the application to be deployed.'
    required: true
  branch_name:
    description: 'The name of the branch currently being deployed.'
    required: true
  deploy_on_sandbox:
    description: 'Set to "true" to enable deployment to the sandbox environment during the ALL_ENV stage.'
    required: false
    default: 'true'
  env_to_deploy:
    description: >
      Specifies the target environment for deployment.
      Use 'ALL_ENV' to update all environments, or 'NO_SYNC' to only update common staging values.
    required: true
  image_tag:
    description: 'The specific image tag to deploy.'
    required: false
  manual:
    description: 'Set to true if the deployment is manual, to reflect this in the commit message.'
    required: false
  rollout:
    description: 'Set to true if the deployment is a rollout, to reflect this in the commit message.'
    required: false
  synced_envs_as_outputs:
    description: 'Set to true to output the list of environments that were synchronized.'
    required: false
    default: 'false'
  update_deployed_at:
    description: 'Set to "true" to update the DEPLOYED_AT environment variable with the current date and time.'
    required: false
    default: 'false'
  release_version:
    description: 'The version of the PROD release to be deployed.'
    required: false

outputs:
  old_image_tag:
    description: 'The old Branch name.'
    value: ${{ steps.remote-values-sync.outputs.old_image_tag }}
  synced_staging_envs:
    description: 'The synced staging environments.'
    value: ${{ steps.remote-values-sync.outputs.synced_staging_envs }}

runs:
  using: "composite"
  steps:
    - id: remote-values-sync
      name: Sync Remote Values with Local Values
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        APP_NAME: ${{ inputs.app_name }}
        BRANCH_NAME: ${{ inputs.branch_name }}
        DEPLOY_ON_SANDBOX: ${{ inputs.deploy_on_sandbox }}
        ENV_TO_DEPLOY: ${{ inputs.env_to_deploy }}
        IMAGE_TAG: ${{ inputs.image_tag }}
        MANUAL: ${{ inputs.manual }}
        ROLLOUT: ${{ inputs.rollout }}
        SYNCED_ENVS_AS_OUTPUTS: ${{ inputs.synced_envs_as_outputs }}
        UPDATE_DEPLOYED_AT: ${{ inputs.update_deployed_at }}
        RELEASE_VERSION: ${{ inputs.release_version }}
      shell: bash
