---
name: 'Update local values'
description: 'Update current_tag value locally and commit changes.'

inputs:
  app_name:
    description: 'The application name that will be deployed.'
    required: true
  branch_name:
    description: 'Current branch name.'
    required: true
  env_to_deploy:
    description: >
      Environment where the image will be deployed.
      If the value is 'ALL_ENV', then all environments will be updated.
    required: true
  image_tag:
    description: 'The image tag that will be deployed.'
    required: true
  rollout:
    description: 'If true, the commit message will specify that is a Rollout.'
    required: false
  update_deployed_at:
    description: 'If "true" the env DEPLOYED_AT will be updated with the current deployment date.'
    required: true

runs:
  using: "composite"
  steps:
    - id: remote-values-sync
      name: Sync Remote Values with Local Values
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        APP_NAME: ${{ inputs.app_name }}
        BRANCH_NAME: ${{ inputs.branch_name }}
        ENV_TO_DEPLOY: ${{ inputs.env_to_deploy }}
        IMAGE_TAG: ${{ inputs.image_tag }}
        ROLLOUT: ${{ inputs.rollout }}
        UPDATE_DEPLOYED_AT: ${{ inputs.update_deployed_at }}
      shell: bash
