---
name: 'Update local values'
description: 'Update current_tag value locally and commit changes.'

inputs:
  app_name:
    description: 'The application name that will be deployed.'
    required: true
    type: string
  env_to_deploy:
    description: 'Environment where the image will be deployed.'
    required: true
    type: string
  image_tag:
    description: 'The image tag that will be deployed.'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - id: update-currenttag-value
      name: Update Current Tag Value in the App remove values repository
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        APP_NAME: ${{ inputs.app_name }}
        ENV_TO_DEPLOY: ${{ inputs.env_to_deploy }}
        IMAGE_TAG: ${{ inputs.image_tag }}
        UPDATE_DEPLOYED_AT: ${{ inputs.update_deployed_at }}
      shell: bash
