---
name: "Helm Template"
description: "Kube Linter Execution for Helm Chart Templates."

inputs:
  app_name:
    description: "The application name."
    required: true
  environments:
    description: "Environments list."
    required: true
  github_token_checkout_values:
    description: "The GitHub token to checkout the helm-chart-values repository."
    required: true
  github_token_checkout_template:
    description: "The GitHub token to checkout the helm-chart-template repository."
    required: true
  github_organization_name_values:
    description: "Organization Name for helm-chart-values repository."
    required: false
    default: fcm-digital
  github_organization_name_template:
    description: "Organization Name for helm-chart-template repository."
    required: false
    default: fcm-digital
  image_tag:
    description: "The image tag that will be used."
    required: true
  helm_chart_template_version:
    description: "Helm Chart Template Version"
    required: true
  helm_version:
    description: "Helm Version."
    required: true
  template_file:
    description: "Template file name to be used."
    required: false

runs:
  using: "composite"
  steps:
    - id: get-branch-name-from-env
      name: Get Branch Name from env
      run: |
        if [ "{{ inputs.environment }}" == "prod" ]; then
          echo "BRANCH_NAME=master" >> $GITHUB_ENV
        else
          echo "BRANCH_NAME=staging" >> $GITHUB_ENV
        fi
      shell: bash

    - id: checkout-helm-chart-values
      name: Checkout helm-chart-values repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.github_organization_name_values }}/helm-chart-${{ inputs.app_name }}-values
        token: ${{ inputs.github_token_checkout_values }}
        ref: ${{ env.BRANCH_NAME }}
        path: helm-chart-values

    - id: checkout-helm-chart-template
      name: Checkout helm-chart-template repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.github_organization_name_template }}/helm-chart-template
        token: ${{ inputs.github_token_checkout_template }}
        ref: ${{ inputs.helm_chart_template_version }}
        path: helm-chart-template

    - id: install-helm
      name: Helm Installation
      uses: azure/setup-helm@v3
      with:
        version: ${{ inputs.helm_version }}

    - id: helm-template-argocd
      name: Helm Template for ArgoCD
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        APP_NAME: ${{ inputs.app_name }}
        ENVIRONMENTS: ${{ inputs.environments }}
        IMAGE_TAG: ${{ inputs.image_tag }}
        TEMPLATE_FILE: ${{ inputs.template_file }}
      shell: bash
