---
name: "Helm Template"
description: "Kube Linter Execution for Helm Chart Templates."

inputs:
  app_name:
    description: "The application name."
    required: true
  environments:
    description: "Environments list (comma separated)."
    required: true
  image_tag:
    description: "The image tag that will be used."
    required: true
  template_file:
    description: "Template file name to be used."
    required: false

  github_app_id:
    description: "The GitHub App ID."
    required: true
  github_app_private_key:
    description: "The GitHub App Private Key."
    required: true
  github_organization_name:
    description: "The GitHub Organization Name."
    required: false
    default: "fcm-digital"

  helm_chart_template_version:
    description: "Helm Chart Template Version"
    required: true
  helm_version:
    description: "Helm Version."
    required: true

runs:
  using: "composite"
  steps:
    - id: app-token
      name: Create GitHub App Token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ inputs.github_app_id }}
        private-key: ${{ inputs.github_app_private_key }}
        owner: ${{ inputs.github_organization_name }}
        repositories: helm-chart-template

    - id: checkout-helm-chart-template
      name: Checkout helm-chart-template repository
      uses: actions/checkout@v6
      with:
        repository: fcm-digital/helm-chart-template
        token: ${{ steps.app-token.outputs.token }}
        ref: ${{ inputs.helm_chart_template_version }}
        path: helm-chart-template

    - id: install-helm
      name: Helm Installation
      uses: azure/setup-helm@v3
      with:
        version: ${{ inputs.helm_version }}

    - id: helm-template-argocd
      name: Helm Template for ArgoCD
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        APP_NAME: ${{ inputs.app_name }}
        ENVIRONMENTS: ${{ inputs.environments }}
        IMAGE_TAG: ${{ inputs.image_tag }}
        TEMPLATE_FILE: ${{ inputs.template_file }}
        HELM_CHART_VALUES_PATH: ${{ inputs.helm_chart_values_path }}
        HELM_CHART_TEMPLATE_PATH: helm-chart-template
      shell: bash
