---
name: 'Get Workflow ID'
description: 'Get the ID of a GitHub workflow based on the workflow file name and repository.'

inputs:
  github_token:
    description: 'The GitHub token to list workflows.'
    required: true
  github_organization_name:
    description: 'The GitHub organization name.'
    required: true
  repository_name:
    description: 'The repository name.'
    required: true
  workflow_file_name:
    description: 'The workflow file name.'
    required: true

outputs:
  workflow_id:
    description: 'The workflow ID.'
    value: ${{ steps.get-workflow-id.outputs.workflow_id }}

runs:
  using: "composite"
  steps:
    - id: list-workflows
      name: List Workflows
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_ORGANIZATION_NAME: ${{ inputs.github_organization_name }}
        REPOSITORY_NAME: ${{ inputs.repository_name }}
        WORKFLOW_FILE_NAME: ${{ inputs.workflow_file_name }}
      run: |
        WORKFLOWS_DATA=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$GITHUB_ORGANIZATION_NAME/$REPOSITORY_NAME/actions/workflows)

        if [[ $? -ne 0 ]] || [[ -z $WORKFLOWS_DATA ]]; then
          echo "Failed to list workflows"
          exit 1
        fi

        echo $WORKFLOWS_DATA

        WORKFLOW_ID=$(echo $WORKFLOWS_DATA | jq '.workflows[] | select(.path | contains("$WORKFLOW_FILE_NAME"))' | jq '.id')

        if [[ $? -ne 0 ]] || [[ -z $WORKFLOW_ID ]]; then
          echo "Failed to get workflow ID"
          exit 1
        fi
        echo "workflow_id=$WORKFLOW_ID" >> $GITHUB_OUTPUT
      shell: bash