---
name: 'Get Workflow ID'
description: 'Get the ID of a GitHub workflow based on the workflow file name and repository.'

inputs:
  github_token:
    description: 'The GitHub token to list workflows.'
    required: true
  github_organization_name:
    description: 'The GitHub organization name.'
    required: true
  repository_name:
    description: 'The repository name.'
    required: true
  workflow_file_name:
    description: 'The workflow file name.'
    required: true

outputs:
  workflow_id:
    description: 'The workflow ID.'
    value: ${{ steps.get-workflow-id.outputs.workflow_id }}

runs:
  using: "composite"
  steps:
    - id: get-workflow-id
      name: Get Workflow ID
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        gh workflow list --repo ${{ inputs.github_organization_name }}/${{ inputs.repository_name }} --json id,name

        # gh api \
        #   -H "Accept: application/vnd.github+json" \
        #   -H "X-GitHub-Api-Version: 2022-11-28" \
        #   /repos/${{ inputs.github_organization_name }}/${{ inputs.repository_name }}/actions/workflows

        # if [[ $? -ne 0 ]] || [[ -z $WORKFLOWS_DATA ]]; then
        #   echo "Failed to list workflows"
        #   exit 1
        # fi

        # echo "WORKFLOWS_DATA: $WORKFLOWS_DATA"

        # WORKFLOW_ID=$(echo $WORKFLOWS_DATA | jq --arg workflowFileName "${{ inputs.workflow_file_name }}" '.workflows[] | select(.path | contains($workflowFileName))' | jq '.id')

        # if [[ $? -ne 0 ]] || [[ -z $WORKFLOW_ID ]]; then
        #   echo "Failed to get workflow ID"
        #   exit 1
        # fi
        # echo "workflow_id=$WORKFLOW_ID" >> $GITHUB_OUTPUT
      shell: bash