---
name: "Authenticate to GCP"
description: "Authenticatio to Google Cloud Platform via WIF or JSON"

inputs:
  setup_gcloud_sdk:
    description: "Enable GCloud SDK setup."
    required: false
    default: "true"
  gcloud_sdk_version:
    description: "The version of the GCloud SDK to use."
    required: false
    default: ">= 544.0.0"
  gcloud_sdk_install_components:
    description: "The components to install with the GCloud SDK."
    required: false
    default: ""

  gcp_wif_project_id:
    description: "The GCP project ID to use for WIF authentication."
    required: true
  gcp_wif_pool:
    description: "The GCP WIF Pool to use for authentication."
    required: true
  gcp_wif_provider:
    description: "The GCP WIF Provider to use for authentication."
    required: true
  gcp_wif_service_account:
    description: "The GCP SA to use for authentication."
    required: true

outputs:
  auth_type:
    description: "The type of authentication used."
    value: WIF
  access_token:
    description: "The access token for GCP."
    value: ${{ steps.auth-gcp-wif.outputs.access_token }}

runs:
  using: "composite"
  steps:
    - id: auth-gcp-wif
      name: Authenticate to GCP via WIF
      uses: google-github-actions/auth@v3
      with:
        token_format: "access_token"
        workload_identity_provider: "projects/${{ inputs.gcp_wif_project_id }}/locations/global/workloadIdentityPools/${{ inputs.gcp_wif_pool }}/providers/${{ inputs.gcp_wif_provider }}"
        service_account: ${{ inputs.gcp_wif_service_account }}

    - name: Set up Cloud SDK
      if: inputs.setup_gcloud_sdk == 'true'
      uses: google-github-actions/setup-gcloud@v3
      with:
        install_components: ${{ inputs.gcloud_sdk_install_components }}
        version: ${{ inputs.gcloud_sdk_version }}

    - id: validate-gcp-auth
      name: Validate GCP authentication
      run: |
        gcloud auth list
      shell: bash

    - id: print-gcloud-versions
      name: Print GCloud command versions
      run: |
        gcloud version
      shell: bash
