---
name: Run make.rb

on:
  workflow_call:
    inputs:
      command:
        description: 'Command for execute in `./make.rb` (default: help)'
        required: false
        default: 'help'
        type: string

      environment:
        description: 'Target environment (default: auto)'
        required: false
        default: 'auto'
        type: string

      gcp_project:
        description: 'Google Cloud project where the resource are (PRO: fcm-platform-pro-9b1e, STG: fcm-platform-stg-a3dc'
        required: false
        default: 'fcm-platform-stg-a3dc'
        type: string

      region:
        required: false
        default: 'europe-west1'
        type: string
        description: 'Region or zone for Google Artifact Registry (default: europe-west1)'

      ruby:
        required: false
        default: "3.1.0"
        type: string
        description: "Ruby version to use with make.rb (default: 3.1.0)"

    secrets:
      gcp_json:
        required: true

env:
  USE_GKE_GCLOUD_AUTH_PLUGIN: True

jobs:
  run-make-rb:
    name: 'Run make.rb'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby }}
          bundler-cache: true

      - run: bundle install && bundle clean --force

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.gcp_json }}
          project_id: ${{ inputs.gcp_project }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: Login to Google Container Registry
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.gcp_json }}

      - name: Login to Google Artifact Registry [${{ inputs.region }}]
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.region }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.gcp_json }}

      - name: 'Run make.rb'
        id: 'run-ruby-maker'
        run: |
          ./make.rb \
          -e "${{ inputs.environment }}" \
          ${{ inputs.command }}
