---
name: 'ArgoCD CLI Installation'
description: 'ArgoCD commands for its CLI installation.'

inputs:
  argocd_cli_version:
    required: false
    type: string
    default: 'v2.8.1'
    description: 'ArgoCD CLI version (default: v2.8.1).'

runs:
  using: "composite"
  steps:
    - id: argocd-cli-install
      name: 'ArgoCD CLI Install'
      shell: bash
      run: |
        curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/download/${{ inputs.argocd_cli_version }}/argocd-linux-amd64
        install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
        rm argocd-linux-amd64
