---
name: 'ArgoCD CLI Installation'
description: 'ArgoCD commands for its CLI installation.'

inputs:
  argocd_cli_version:
    required: false
    type: string
    default: '5.13.6'
    description: 'ArgoCD CLI version (default: 5.13.6).'

runs:
  using: "composite"
  steps:
    - id: argocd-cli-install
      name: 'ArgoCD CLI Install'
      shell: bash
      run: |
        curl -sSL https://github.com/argoproj/argo-cd/releases/download/${{ inputs.argocd_cli_version }}/argocd-linux-amd64 -o /usr/local/bin/argocd